include: all_lint_rules.yaml
analyzer:
  errors:
    import_of_legacy_library_into_null_safe: ignore
    included_file_warning: error
    annotate_overrides: error
    prefer_final_locals: error
    sized_box_for_whitespace: error
    use_key_in_widget_constructors: error
    no_logic_in_create_state: error
    avoid_unnecessary_containers: error
    unnecessary_const: error
    no_duplicate_case_values: error
    prefer_const_constructors: error

linter:
  rules:
    avoid_dynamic_calls: false
    overridden_fields: false
    leading_newlines_in_multiline_strings: false
    use_late_for_private_fields_and_variables: false
    invariant_booleans: false
    cast_nullable_to_non_nullable: false
    avoid_field_initializers_in_const_classes: false
    use_if_null_to_convert_nulls_to_bools: false
    file_names: false
    sort_pub_dependencies: false
    prefer_null_aware_operators: false
    avoid_redundant_argument_values: true
    do_not_use_environment: false
    unnecessary_string_escapes: false
    unnecessary_lambdas: false
    prefer_mixin: false
    prefer_if_elements_to_conditional_expressions: false
    use_setters_to_change_properties: false
    use_build_context_synchronously: false
    directives_ordering: true
    public_member_api_docs: false
    comment_references: true
    sort_constructors_first: false
    sort_unnamed_constructors_first: false
    always_put_control_body_on_new_line: false
    omit_local_variable_types: false
    prefer_constructors_over_static_methods: false
    prefer_final_locals: true
    only_throw_errors: false
    prefer_relative_imports: false
    non_constant_identifier_names: false
    avoid_returning_this: false
    avoid_catching_errors: false
    constant_identifier_names: false
    prefer_function_declarations_over_variables: false
    avoid_classes_with_only_static_members: false
    avoid_function_literals_in_foreach_calls: false
    cascade_invocations: false
    prefer_double_quotes: false
    always_specify_types: false
    prefer_expression_function_bodies: false
    always_put_required_named_parameters_first: false
    avoid_as: false
    avoid_catches_without_on_clauses: false
    lines_longer_than_80_chars: false
    avoid_annotating_with_dynamic: false
    always_use_package_imports: false
    no_default_cases: false
    prefer_asserts_with_message: false
    avoid_types_on_closure_parameters: false
    diagnostic_describe_all_properties: false
    avoid_positional_boolean_parameters: false
